# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastfitz',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/fastfitz',
                'lib_path': 'fastfitz'},
  'syms': { 'fastfitz.core': { 'fastfitz.core.fitz.Document.search_for': ('core.html#fitz.document.search_for', 'fastfitz/core.py'),
                               'fastfitz.core.fitz.Document.text': ('core.html#fitz.document.text', 'fastfitz/core.py'),
                               'fastfitz.core.fitz.Page._repr_png_': ('core.html#fitz.page._repr_png_', 'fastfitz/core.py'),
                               'fastfitz.core.fitz.Page.preview': ('core.html#fitz.page.preview', 'fastfitz/core.py')},
            'fastfitz.skill': {}}}
