"""Read, search, and visually preview PDFs with `fitz` (PyMuPDF)

Docs: https://AnswerDotAI.github.io/fastfitz/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/00_core.ipynb #879a271c
import fitz
from functools import reduce
from operator import or_
from fastcore.utils import *
from IPython.display import Image

# %% ../nbs/00_core.ipynb #840063c3
@patch
def text(self:fitz.Document, pages=None)->str:
    "Plain text of `pages` (default: all), with `--- page N ---` separators"
    ps = list(self) if pages is None else [self[i] for i in pages]
    return '\n'.join(f'--- page {p.number} ---\n{p.get_text().rstrip()}' for p in ps)

# %% ../nbs/00_core.ipynb #3e3d2bbd
@patch
def search_for(self:fitz.Document, q)->list:
    "`(page, rects)` for each page where `q` matches; pages without hits are dropped"
    return [(p, r) for p in self if (r := p.search_for(q))]

# %% ../nbs/00_core.ipynb #e5ce4599
@patch
def preview(self:fitz.Page, q=None, clip=None, dpi=150):
    "Render as a PNG `Image`: the whole page, a `clip` rect, or the union of rects matching `q`"
    if q:
        rects = self.search_for(q)
        if not rects: raise ValueError(f'{q!r} not found on page {self.number}')
        clip = reduce(or_, rects)
    return Image(data=self.get_pixmap(dpi=dpi, clip=clip).tobytes('png'))

# %% ../nbs/00_core.ipynb #86d8f857
@patch
def _repr_png_(self:fitz.Page): return self.preview().data
